#!/bin/sh

# The following is necessary to use Anaconda's python.
source ~/.bash_profile
# Change current working directory
cd -- "$(dirname "$BASH_SOURCE")"
# Install FlowCal
python -m pip install --user -r requirements.txt --no-cache-dir
python setup.py install
