#!/bin/sh

# Change current working directory
cd -- "$(dirname "$BASH_SOURCE")"
# Install fc
sudo pip install -r requirements.txt
sudo python setup.py install
# Pause
read -p "Press [Enter] to finish..."